
// Generated by https://quicktype.io

export interface BancosBD {
    entidaD_FINANCIERA: string;
    descripcion:        string;
}

export class Bancos {
    banco: string;
    nombre: string;

    constructor (banco: string, nombre: string ){
        this.banco = banco;
        this.nombre = nombre;
    }
}
