
export class Cardex {
    codCliente: string;
    codProducto: string;
    desProducto: string;
    tipoDocumento: string;
    fecha: Date;
    aplicado: boolean;
    cantInventario: number;
    cantPedido: number;
    descuento: number;
    precio?: number;

    constructor ( idClient: string, idProd: string, desProd: string, tipoDocum: string, fecha: Date, cantInventario: number, cantPedido: number, descuento: number ){
        this.codCliente = idClient;
        this.codProducto = idProd;
        this.desProducto = desProd;
        this.tipoDocumento = tipoDocum;
        this.fecha = fecha;
        this.aplicado = false;
        this.cantInventario = cantInventario;
        this.cantPedido = cantPedido;
        this.descuento = descuento;
    }
}

export class CardexBD {
    ruta: string;
    tipO_DOCUMENTO: string;
    fecha: Date;
    cliente: string;
    articulo: string;
    cantidad: number;
    descuento: number;

    constructor ( ruta: string, tipDocu: string, fecha: Date, clienteId: string, codProd: string, cantidad: number, descuento: number ){
        this.ruta = ruta;
        this.tipO_DOCUMENTO = tipDocu;
        this.fecha = fecha;
        this.cliente = clienteId;
        this.articulo = codProd;
        this.cantidad = cantidad;
        this.descuento = descuento;
    }
}

// Generated by https://quicktype.io

export interface SugeridoBD {
    cliente:       string;
    articulo:      string;
    canT_SUGERIDA: number;
    ruta:          string;
}


