
export class Cardex {
    constructor(
        public codCliente: string,
        public factura:    string,
        public codProducto: string,
        public desProducto: string,
        public tipoDocumento: string,
        public fecha: Date,
        public cantInventario: number,
        public cantPedido: number,
        public descuento: number,
        public montoDescuento: number,
        public impuesto: number,
        public monto: number,
        public precio: number,
        public linea: number = 0,
        public bodega: string = '',
        public descGeneral: number = 0,
        public aplicado: boolean = false,
        public cantDev: number = 0
    ){}
}

export class CardexBD {
    constructor(
        public ruta: string,
        public tipO_DOCUMENTO: string,
        public fecha: Date,
        public cliente: string,
        public articulo: string,
        public cantidad: number,
        public descuento: number,
        public factura: string,
        public preciO_UNITARIO: number,
        public totaL_IMPUESTO1: number,
        public desC_TOT_LINEA: number,
        public preciO_TOTAL: number,
        public linea: number,
        public desC_TOT_GENERAL: number,
        public bodega: string
    ){}
}

/*
export class DevolucionesDet {
    constructor (
        public numFactura:  string,
        public fechaFac:    Date,
        public cliente:     string,
        public articulo:    string,
        public descArticulo: string,
        public precio:      number,
        public cantidad:    number,
        public cantDevuelta: number,
        public descuento:   number,
        public impuestos:   number,
        public monto:       number,      /// Agregarle los campos nuevos: Linea, Bodega, etc.
    ){}
}*/

// Generated by https://quicktype.io

export interface SugeridoBD {
    cliente:       string;
    articulo:      string;
    canT_SUGERIDA: number;
    ruta:          string;
}


