
export class Cliente {
    id: string;
    nombre: string;
    direccion: string;
    tipoContribuyente: string;   // F: Fisico, J: Juridico
    contribuyente: string;       // cedula del representante
    razonSocial: string;         // nombre legal
    telefonoContacto: string; 
    nombreContacto: string;
    montoCredito: number;
    limiteCredito: number;
    saldoCredito: number;
    diasCredito: number;
    listaPrecios: number;
    descuento: number;
    tipoImpuesto: number;
    tarifa: number;              // Refiere al tipo de impuesto
    porcentajeTarifa: number;    // Refiere al porcentaje del IVA
    divGeografica1: string;
    divGeografica2: string;
    moroso: boolean;
    email: string;
    latitud: number;
    longitud: number;
    letraCambio: boolean;
    compania: string;

    constructor(id: string, nombre: string, dir: string, tipoCont: string, contri: string, razonSocial: string, telContacto: string,
        nomContacto: string, credito: number, limCredito: number, diasCred: number, listaPrecio: number, descuento: number, tipoImp: number,
        tarifa: number, porTarifa: number, divGeo1: string, divGeo2: string, moroso: string, email: string, lat: number, lon: number, letraCambio: string, compania: string ){
        this.id = id;
        this.nombre = nombre;
        this.direccion = dir;
        this.tipoContribuyente = tipoCont;
        this.contribuyente = contri;
        this.razonSocial = razonSocial;
        this.telefonoContacto = telContacto;
        this.nombreContacto = nomContacto;
        this.montoCredito = credito;
        this.limiteCredito = limCredito;
        this.diasCredito = diasCred;
        this.listaPrecios = listaPrecio;
        this.descuento = descuento;
        this.tipoImpuesto = tipoImp;
        this.tarifa = tarifa;
        this.porcentajeTarifa = porTarifa;
        this.divGeografica1 = divGeo1;
        this.divGeografica2 = divGeo2;
        if (moroso == 'N'){
            this.moroso = false
        } else {
            this.moroso = true;
        }
        this.email = email;
        this.latitud = lat;
        this.longitud = lon;
        if (letraCambio === 'S'){
            this.letraCambio = true;
        } else {
            this.letraCambio = false;
        }
        this.compania = compania;
        this.saldoCredito = 0;

    }
}

export interface ClienteBD {
    cod_Zon:        string,
    cod_Clt:        string,
    nom_Clt:        string,
    dir_Clt:        string,
    tipo_Tarifa:    string,
    porc_Tarifa:    number,
    tipo_Impuesto:  string,
    cod_Cnd:        string,
    cod_Pais:       string,
    COD_CIA:        string,
    contribuyente:  string,
    descuento:      number,
    division_Geografica1: string,
    division_Geografica2: string,
    ind_Mon:        string,
    lim_Cre:        number,
    lst_Pre:        number,
    nom_Cto:        string,
    num_Tel:        string,
    razonsocial:    string,
    tipo_Contribuyente: string,
    moroso:         string,
    e_MAIL:         string,
    longitud:       number,
    latitud:        number,
    altitud:        number,
    fechA_ACTUALIZACION_UBICACION: Date,
    usa_Letra:      string,
    coD_CIA:        string,
}

// Generated by https://quicktype.io

export interface ClienteRT {
    cliente:                       string;
    nombre:                        string;
    latitud:                       number;
    longitud:                      number;
    altitud:                       number;
    fechA_ACTUALIZACION_UBICACION: Date;
    noteExistsFlag:                number;
    recordDate:                    Date;
    rowPointer:                    string;
    createdBy:                     string;
    updatedBy:                     string;
    createDate:                    Date;
}

export interface ClientePut {
    RUTA:                          string;
    FECHA_MODIFICACION:            Date;
    CLIENTE:                       string;
    RUBRO1_CLIENTE:                string;
    RUBRO2_CLIENTE:                string;
    RUBRO3_CLIENTE:                string;
}

// Generated by https://quicktype.io

export interface Categorias {
    categoriA_CLIENTE: string;
    descripcion:       string;
}

export interface ClienteNuevo {
    ID:         string;
    Ruta:       string;
    Fecha:      Date;
    Nombre:     string;
    Razon_Social: string;
    Representante: string;
    Categoria:  string;
    Dia_Visita: string;
    Dia_Entrega: string;
    Hora_Entrega: string;
    Contacto:   string;
    Telefono:   string;
    Email:      string;
    Provincia:  string;
    Canton:     string;
    Distrito:   string;
    Direccion:  string;
    Latitud:    number;
    Longitud:   number;
    Estado:     string;
    Ruta_Distribucion: string;
}

export interface RutasCanton {
    Ruta: string;
    Provincia: string;
    Canton: string;
  }



