
export class Pen_Cobro {
    numeroRuta: string;
    tipoDocumen: string;
    numeroDocumen: string;
    codCliente: number;
    saldoDolar: number;
    saldoLocal: number;
    montoDolar: number;
    montoLocal: number;
    fechaDoc: Date;
    fechaVencimiento: Date;
    condicionPago: string;
    pago: boolean;

    constructor ( ruta: string, tipDoc: string, numDoc: string, codCliente: number, saldoD: number, saldoL: number, montoD: number, 
                  montoL: number, fecDoc: Date, fecVen: Date, conPago: string ){
        this.numeroRuta = ruta;
        this.tipoDocumen = tipDoc;
        this.numeroDocumen = numDoc;
        this.codCliente = codCliente;
        this.saldoDolar = saldoD;
        this.saldoLocal = saldoL;
        this.montoDolar = montoD;
        this.montoLocal = montoL;
        this.fechaDoc = fecDoc;
        this.fechaVencimiento = fecVen;
        this.condicionPago = conPago;
        this.pago = false;
    }
}

// Generated by https://quicktype.io

export interface CxCBD {
    coD_CIA:        string;
    coD_ZON:        string;
    coD_TIP_DC:     string;
    nuM_DOC:        string;
    coD_CLT:        string;
    saldO_DOLAR:    number;
    saldO_LOCAL:    number;
    montO_DOLAR:    number;
    montO_LOCAL:    number;
    feC_DOC_FT:     string;
    feC_PRO:        string;
    feC_VEN:        string;
    inD_MON:        string;
    inD_ANL:        string;
    tiP_CMB_DOL:    number;
    condicioN_PAGO: string;
    subtotal:       number;
    tiP_CMB_LOC:    number;
}

