export const DataClientes = [
    {
        id: 1,
        nombre: "Mas x Menos Guachipelin",
        direccion: "Guachipelin Escazu",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 2,
        nombre: "Auto Mercado Guachipelin",
        direccion: "Guachipelin Escazu",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 3,
        nombre: "Mas x Menos Escazu",
        direccion: "San Rafael de Escazu",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 4,
        nombre: "Mas x Menos Santa Ana",
        direccion: "Santa Ana",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 5,
        nombre: "Mega Super Santa Ana",
        direccion: "Santa Ana",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 6,
        nombre: "Mega Super San Joaquin",
        direccion: "Flores, Heredia",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 7,
        nombre: "Walmart Heredia",
        direccion: "San Francisco, Heredia",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 8,
        nombre: "Mas x Menos San Francisco",
        direccion: "San Francisco, Heredia",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 9,
        nombre: "Maxi Pali Cubijuqui",
        direccion: "Mercedes Sur Heredia",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 10,
        nombre: "Pali Heredia Mercado",
        direccion: "Heredia",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 11,
        nombre: "Pali Paseo Colon",
        direccion: "Paseo Colon, San Jose",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    },
    {
        id: 12,
        nombre: "Auto Mercado San Pedro",
        direccion: "San Pedro de Montes de Oca",
        montoCredito: 2000000,
        limiteCredito: 5000000,
    }
]
