export const DataProductos = [
    {
        id: 11335,
        nombre: "Cerveza Peroni Nastro Azurro",
        categoria: "Cervezas",
        precio: 950,
        grupoPromocional: 1,
        imagen: "../../assets/img/11335.png",
    },
    {
        id: 11476,
        nombre: "Cerveza Asahi Dry Botella",
        categoria: "Cervezas",
        precio: 950,
        grupoPromocional: 1,
        imagen: "../../assets/img/11476.png",
    },
    {
        id: 4603,
        nombre: "Cerveza Estrella Damm Botella",
        categoria: "Cervezas",
        precio: 950,
        grupoPromocional: 1,
        imagen: "../../assets/img/4603.png",
    },
    {
        id: 11136,
        nombre: "Cerveza Malquerida Botella",
        categoria: "Cervezas",
        precio: 950,
        grupoPromocional: 1,
        imagen: "../../assets/img/11136.png",
    },
    {
        id: 11560,
        nombre: "Cerveza Erdinger Weisbier Botella 500ml",
        categoria: "Cervezas",
        precio: 950,
        grupoPromocional: 1,
        imagen: "../../assets/img/11560.png",
    },
    {
        id: 10048,
        nombre: "Aderezo Mostaza y Miel 200ml McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10048.png",
    },
    {
        id: 10051,
        nombre: "Aderezo Papa Ensalada Ranch 200ml McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10051.png",
    },
    {
        id: 10053,
        nombre: "Aderezo Italiano Doypack 200ml McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10053.png",
    },
    {
        id: 10054,
        nombre: "Aderezo Caesar Doypack 200ml McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10054.png",
    },
    {
        id: 10052,
        nombre: "Aderezo Mil Islas 200ml McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10052.png",
    },
    {
        id: 10796,
        nombre: "Aderezo Cilantro 200ml McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10796.png",
    },
    {
        id: 10985,
        nombre: "Mayonesa con Chiplote 350g McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/10985.png",
    },
    {
        id: 3618,
        nombre: "Mayonesa Doypack 200g McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/3618.png",
    },
    {
        id: 11354,
        nombre: "Mayonesa Fiestamix 350g McCormick",
        categoria: "Salsas",
        precio: 400,
        grupoPromocional: 2,
        imagen: "../../assets/img/11354.png",
    },
    {
        id: 2307,
        nombre: "Aceite Sesamo Roland 185ml",
        categoria: "Aceites",
        precio: 1100,
        grupoPromocional: 3,
        imagen: "../../assets/img/2307.png",
    },
    {
        id: 2550,
        nombre: "Aceite Oliva Extra Virgen 750ml Ybarra",
        categoria: "Aceites",
        precio: 1100,
        grupoPromocional: 3,
        imagen: "../../assets/img/2550.png",
    },
    {
        id: 2527,
        nombre: "Aceite Oliva 250ml Ybarra",
        categoria: "Aceites",
        precio: 1100,
        grupoPromocional: 3,
        imagen: "../../assets/img/2527.png",
    },
    {
        id: 1670,
        nombre: "Tortita de Arooz Integral con Quinoa 130g Santiveri",
        categoria: "Snacks",
        precio: 500,
        grupoPromocional: 4,
        imagen: "../../assets/img/1670.png",
    },
    {
        id: 1635,
        nombre: "Tortita de Arooz sin Sal 130g Santiveri",
        categoria: "Snacks",
        precio: 500,
        grupoPromocional: 4,
        imagen: "../../assets/img/1635.png",
    },
    {
        id: 1630,
        nombre: "Corn Flakes Noglut 250g Santiveri",
        categoria: "Snacks",
        precio: 500,
        grupoPromocional: 4,
        imagen: "../../assets/img/1630.png",
    },
    {
        id: 11613,
        nombre: "Snack de Guisante Sabor a Jamon 55g Bicentury",
        categoria: "Snacks",
        precio: 500,
        grupoPromocional: 4,
        imagen: "../../assets/img/11613.png",
    },
    {
        id: 11614,
        nombre: "Snack de Lentejas sabor a Cebolla Caramelizada 55g Bicentury",
        categoria: "Snacks",
        precio: 500,
        grupoPromocional: 4,
        imagen: "../../assets/img/11614.png",
    },
    {
        id: 10611,
        nombre: "Tortita de Maiz Jamon Iberico 70g Bicentury",
        categoria: "Snacks",
        precio: 500,
        grupoPromocional: 4,
        imagen: "../../assets/img/10611.png",
    },
]
