
// Generated by https://quicktype.io

export class Email {
    toEmail: string;
    subject: string;
    body:    string;

    constructor (to: string, sub: string, body: string){
        this.toEmail = to;
        this.subject = sub;
        this.body = body;
    }
}

