export const environment = {
  production: true,
  rutasURL: 'http://api_isa_test.soportecr.xyz/api/rutas',
  clientesURL: 'http://api_isa_test.soportecr.xyz/api/clientes/',
  productosURL: 'http://api_isa_test.soportecr.xyz/api/productos/',
  PedEncaURL: 'http://api_isa_test.soportecr.xyz/api/FAC_enc_ped/',
  PedDetaURL: 'http://api_isa_test.soportecr.xyz/api/FAC_det_ped/',
  CardexURL: 'http://api_isa_test.soportecr.xyz/api/ISA_Estad_Ventas/',
  CxCURL: 'http://api_isa_test.soportecr.xyz/api/cxc/',
  RecEncaURL: 'http://api_isa_test.soportecr.xyz/api/RecEnca/',
  RecDetaURL: 'http://api_isa_test.soportecr.xyz/api/RecDeta/',
  Existencias: 'http://api_isa_test.soportecr.xyz/api/Existencias/',
  BancosURL: 'http://api_isa_test.soportecr.xyz/api/Bancos/',
  ChequeURL: 'http://api_isa_test.soportecr.xyz/api/Cheque/',
  cantLineasMaxPedido: 35,
  adminClave: '@dmin2021*',
  prdMode: false,
};
